include: "rules/data.smk"
include: "rules/utils.smk"
include: "rules/mapping.smk"
include: "rules/octopus.smk"
include: "rules/prosolo.smk"
include: "rules/strelka2.smk"
include: "rules/sccaller.smk"
include: "rules/monovar.smk"
include: "rules/sciphi.smk"
include: "rules/evaluate.smk"

localrules: all

rule all:
    input:
        expand("results/eval/{project}/{test}.{reference}.{mapper}.{caller}.{sample}.vs.{control}.{filter}.{match}.vcfeval", \
            project = config["project"], \
            test = config["test"], \
            caller = config["callers"], \
            reference = config["reference"], \
            mapper = config["mapper"], \
            sample = config["groups"]["cells"], \
            control = config["groups"]["controls"], \
            filter = ["pass", "raw"], \
            match = ["GT", "AL"]),
        expand("results/eval/{project}/{test}.{reference}.{mapper}.{caller}.{sample}.{filter}.somatics.vcfeval", \
            project = config["project"], \
            test = config["test"], \
            caller = config["callers"], \
            reference = config["reference"], \
            mapper = config["mapper"], \
            sample = config["groups"]["cells"] if "normals" in config["groups"] else [], \
            filter = ["pass", "raw"]),
        expand("results/eval/{project}/{test}.{reference}.{mapper}.{caller}.{filter}.{match}.{control}.{targets}.isec", \
            project = config["project"], \
            test = config["test"], \
            caller = config["callers"], \
            reference = config["reference"], \
            mapper = config["mapper"], \
            sample = config["groups"]["cells"], \
            control = config["subclonal_control"] if "subclonal_control" in config else [], \
            targets = config["subclonal_targets"] if "subclonal_targets" in config else [], \
            filter = ["pass", "raw"], \
            match = ["GT", "AL"]),
